"""Writing the evaluation report as JSON and as Markdown.

The JSON holds every number; the Markdown is a readable view of the same
numbers and adds nothing that is not in the JSON.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from .data import LEGITIMATE

MODEL_ORDER = ("rules", "isolation_forest", "gradient_boosting")
DISCLAIMER = (
    "All data in this report is synthetic, generated by `gil generate` from the parameters in "
    "`src/gil/config.py`. The numbers describe how the models behave on that simulation and say "
    "nothing about real players. A flag is a statistical signal for a human to review, never proof "
    "of cheating: every false positive is an innocent player accused."
)


def _clean(x: Any) -> Any:
    """JSON-safe copy: infinite thresholds become the strings "inf" / "-inf"."""
    if isinstance(x, dict):
        return {str(k): _clean(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [_clean(v) for v in x]
    if hasattr(x, "item"):  # numpy scalar
        x = x.item()
    if isinstance(x, float) and math.isinf(x):
        return "inf" if x > 0 else "-inf"
    return x


def to_json(report: dict) -> str:
    return json.dumps(_clean(report), indent=2, sort_keys=False, allow_nan=False)


def write(report: dict, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    js, md = out_dir / "report.json", out_dir / "report.md"
    js.write_text(to_json(report) + "\n")
    md.write_text(to_markdown(report))
    return js, md


def _pct(x: float, digits: int = 1) -> str:
    return f"{100 * x:.{digits}f}%"


def _models(section: dict) -> list[str]:
    names = list(section)
    return sorted(names, key=lambda n: MODEL_ORDER.index(n) if n in MODEL_ORDER else len(MODEL_ORDER))


def _thr(t: Any) -> str:
    return t if isinstance(t, str) else f"{t:.4g}"


def _task_section(title: str, task: dict, legit: tuple[str, ...], unit: str, note: str = "") -> list[str]:
    models = task["models"]
    names = _models(models)
    first = models[names[0]]
    lines = [f"## {title}", ""]
    lines.append(f"Positives: {', '.join(task['positives'])}. Evaluated {unit}s: {first['n_units']}, "
                 f"base rate {first['base_rate']:.3f}." + (f" {note}" if note else ""))
    lines += ["", "| Model | PR-AUC | Threshold | Precision | Recall | FPR on test (95% CI) | TP | FP | TN | FN |",
              "|---|---|---|---|---|---|---|---|---|---|"]
    for n in names:
        r = models[n]
        c = r["confusion"]
        lo, hi = r["fpr_ci95"]
        thr = f"{math.ceil(r['threshold'])} rules" if r.get("rules") and not isinstance(r["threshold"], str) \
            else _thr(r["threshold"])
        lines.append(f"| {n} | {r['pr_auc']:.3f} | {thr} | {r['precision']:.3f} | "
                     f"{r['recall']:.3f} | {_pct(r['fpr'], 2)} ({_pct(lo)} to {_pct(hi)}) | "
                     f"{c['tp']} | {c['fp']} | {c['tn']} | {c['fn']} |")
    lines += ["", f"Flagged per segment at the operating threshold ({unit}s flagged / {unit}s in the segment):", ""]
    segs = list(first["segments"])
    segs = [s for s in segs if s in legit] + [s for s in segs if s not in legit]
    lines += ["| Segment | Legitimate | " + " | ".join(names) + " |", "|---|---|" + "---|" * len(names)]
    for s in segs:
        cells = []
        for n in names:
            g = models[n]["segments"][s]
            cells.append(f"{g['flagged']}/{g['n']} ({_pct(g['rate'])})")
        lines.append(f"| {s} | {'yes' if s in legit else 'no'} | " + " | ".join(cells) + " |")
    lines += ["", "False-positive budget sweep (threshold chosen on validation for each budget, measured on test):", "",
              "| Model | Budget | Precision | Recall | FPR on test |", "|---|---|---|---|---|"]
    for n in names:
        for w in models[n]["sweep"]:
            lines.append(f"| {n} | {_pct(w['budget'])} | {w['precision']:.3f} | {w['recall']:.3f} | {_pct(w['fpr'], 2)} |")
    for n in names:
        rules = models[n].get("rules")
        if rules:
            lines += ["", f"Rule cutoffs ({n}, fitted on legitimate training {unit}s; the score is the number of rules that fire):", ""]
            lines += ["| Feature | Suspicious when | Cutoff |", "|---|---|---|"]
            lines += [f"| {f} | {v['suspicious_when']} | {v['cutoff']:.4g} |" for f, v in rules.items()]
    lines.append("")
    return lines


def to_markdown(report: dict) -> str:
    d, cfg = report["data"], report["config"]
    lines = ["# Game integrity evaluation report", "", f"> {DISCLAIMER}", ""]
    lines.append(f"Data: {d['players']} synthetic players, {d['decisions']} decisions, seed {d['seed']}, "
                 f"fingerprint `{d['fingerprint']}`. Evaluation seed {cfg['seed']}. Operating threshold chosen on "
                 f"the `{cfg['threshold_split']}` split so that at most {_pct(cfg['budget'])} of legitimate units are "
                 f"flagged; numbers reported on the `{cfg['eval_split']}` split.")
    if cfg["exclude_groups"]:
        lines.append(f"Feature groups left out: {', '.join(cfg['exclude_groups'])}.")
    lines.append("")
    segs = sorted({s for c in d["split_segment_counts"].values() for s in c})
    lines += ["Players per split and segment:", "", "| Split | " + " | ".join(segs) + " |"]
    lines.append("|---|" + "---|" * len(segs))
    for split, counts in d["split_segment_counts"].items():
        lines.append(f"| {split} | " + " | ".join(str(counts.get(s, 0)) for s in segs) + " |")
    lines.append("")

    pt = report["player_task"]
    lines += _task_section("Player task: bots and RTA users", pt, LEGITIMATE, "player")
    oot = pt.get("out_of_task_colluders", {})
    if oot:
        parts = [f"{n} {v['flagged']}/{v['n']}" for n, v in oot.items()]
        lines += ["Colluders in the test split are left out of the player task. Flagged by the player models anyway: "
                  + ", ".join(parts) + ".", ""]
    if report.get("pair_task"):
        pr = report["pair_task"]
        note = (f"Candidate pairs (met in at least {cfg['min_shared_sessions']} sessions): "
                f"{pr['candidate_pairs']} across all splits; a pair is evaluated when both players are in the split.")
        lines += _task_section("Pair task: colluding pairs", pr, ("friends", "other"), "pair", note)

    rob = report.get("robustness") or {}
    if rob:
        lines += ["## Robustness: frozen models on new populations", "",
                  "Each scenario draws a new population with a changed generator; the models and thresholds are the "
                  "ones fitted above, unchanged. `fresh_population` uses the unchanged generator with a new seed.", "",
                  "| Scenario | Model | PR-AUC | Precision | Recall | Bots flagged | RTA flagged | Legitimate FPR | Most flagged legitimate segment |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for scen, models in rob.items():
            for n in _models(models):
                r = models[n]
                s = r["segments"]
                pos = [f"{s[k]['flagged']}/{s[k]['n']}" if k in s else "n/a" for k in ("bot", "rta")]
                legit = [(v["rate"], k) for k, v in s.items() if k in LEGITIMATE]
                rate, worst = max(legit)
                lines.append(f"| {scen} | {n} | {r['pr_auc']:.3f} | {r['precision']:.3f} | {r['recall']:.3f} | "
                             f"{pos[0]} | {pos[1]} | {_pct(r['fpr'], 2)} | {worst} {_pct(rate)} |")
        lines.append("")
    return "\n".join(lines)
